name: Docker Lint

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/hadolint.yml'

permissions:
  contents: read

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run Hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile
